### PR TITLE
feat: add i18n

### PR DESCRIPTION
**Pull request by ArFnds**
Add i18n using [sergiodxa/remix-i18next](https://github.com/sergiodxa/remix-i18next)

- ✅ SSR
- ✅ Client side
- ✅ Auto detect locale
- ✅ Local can be given in query : /login?lng=fr

### CODE REVIEW

**Comment by rphlmr** [comment]
Thanks for your contribution. I fixed cypress test for you ;)

**Comment by rphlmr** [comment]
Let me know if your PR is complete so that I merge It asap :)

**Comment by ArFnds** [comment]
I think everything is complete 👍

**Comment by rphlmr** [comment]
Thanks

**Pull request merged**
